### ISSUE TITLE
[EPIC] Arbitration

### ISSUE THREAD

**Issue by benedictvscriticus** [SmartInvoiceXYZ/smart-invoice#209]
- [ ]  hanges to the frontend
- [ ] restricting arbitration provider selection whenever the invoice value falls below 1,000 USD to custom arbitration provider and Smart Invoice
- [ ] restricting arbitration provider selection upon creation for invoices <1,000 USD
- [ ] adding acknowledge checkbox that arbitration provider defaults to in-house arbitration when invoice value falls below 1,000 USD
- [ ] add a disclaimer for users stating that Smart Invoice will become the default arbitration provider when invoice value falls below 1,000 USD
- [ ] adding Kleros to the provider selector
- [ ] adding tooltips explaining the fee structure for smart invoice, Kleros, and LexDAO
- [ ] adding info box suggesting Gnosis and Polygon as networks for <1,000 USD invoices if LexDAO is desired
